name: on-push-user-acceptance

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
        - name: "grab commit"
          uses: actions/checkout@v2

        - name: build
          run: ./run b

        - name: test
          run: ./run t b

  clean-install:

    runs-on: ubuntu-latest

    steps:
        - name: "grab commit"
          uses: actions/checkout@v2

        - name: "clean build"
          run: ./run c

        - name: "default in-tree install"
          run: ./run i

        - name: "check lib installed"
          uses: andstor/file-existence-action@v1
          with:
            files: "install/libTiledBytes.a, install/tiledbytes.hpp"
